defaults:
  genService: enabled
  debug: false
  replicaCount: 1
  image: powerful<POWERFUL_BUNDLE>
  args:
  - demo
  tag: "<POWERFUL_TAG>"
  hub: zhranklin
  labels: {}
  deployName: '{{- .name }}{{ if .version }}-{{ .version }}{{ end }}'
  deployLabels: {}
  serviceLabels: {}
  annotations: {}
  deployAnnotations: {}
  serviceAnnotations: {}
  nodeSelector: {}
  imagePullSecrets: {}
  resources: {}
ingressHost: ""
cases: {}
apps: []
