defaults:
  genService: true
  debug: false
  replicaCount: 1
  image: powerful<POWERFUL_BUNDLE>
  args:
  - demo
  tag: "<POWERFUL_TAG>"
  hub: zhranklin
  labels: {}
  deployName: '{{- .name }}{{ if .version }}-{{ .version }}{{ end }}'
  deployLabels: {}
  serviceLabels: {}
  annotations: {}
  deployAnnotations: {}
  serviceAnnotations: {}
  nodeSelector: {}
  imagePullSecrets: {}
  resources: {}
  javaOpts:
    dubboDependsOn: |-
      {{- if eq .protocol "dubbo" -}}
        -DdubboDependsOn=
        {{- range $_, $app := append .Values.apps .Values.cases -}}
          {{- if eq ($app.protocol | default $.Values.defaults.protocol) "dubbo" -}}
            {{- $app.Name | default $app.name -}},
          {{- end -}}
        {{- end -}}
      {{- end -}}
ingressHost: ""
cases: {}
apps: []
