e2e:
  overrideYaml:
    framew:
      type: springboot2.1
      application:
        name: framew-e2e
      config:
        appId: framew-e2e
powerful:
  tag: "201911071025"
  hub: "hub.c.163.com/qingzhou"
  zk: "10.182.2.122:2181"
  services:
    framew-demo-grpc-a:
      image: powerful-springboot-2
      targetPort: 9547
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-grpc-a -Dframew.log.level=debug -Dframew.config.debug=true -Dgrpc.server.port=9547"
      overrideYaml:
        framew:
          type: grpc
          application:
            name: grpc-a
            tags:
              - key: k3
                value: v3
          config:
            appId: grpc-a
    framew-demo-grpc-b:
      image: powerful-springboot-grpc
      targetPort: 9548
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-grpc-b -Dframew.log.level=debug -Dframew.config.debug=true -Dgrpc.server.port=9548"
      overrideYaml:
        framew:
          type: grpc
          application:
            name: grpc-b
            tags:
              - key: k1
                value: v1
          config:
            appId: grpc-b
    framew-demo-grpc-b2:
      image: powerful-springboot-grpc
      targetPort: 9549
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-grpc-b -Dframew.log.level=debug -Dframew.config.debug=true -Dgrpc.server.port=9549"
      overrideYaml:
        framew:
          type: grpc
          application:
            name: grpc-b
            tags:
              - key: k2
                value: v2
          config:
            appId: grpc-b
    framew-demo-http-a:
      image: powerful-springboot-2
      targetPort: 8890
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-http-a -Dframew.log.level=debug -Dframew.config.debug=true -Dserver.port=8890"
      overrideYaml:
        framew:
          type: springboot2.1
          application:
            name: http-a
            tags:
              - key: k3
                value: v3
          config:
            appId: http-a
    framew-demo-http-b:
      image: powerful-springboot-a
      targetPort: 8891
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-http-b -Dframew.log.level=debug -Dframew.config.debug=true -Dserver.port=8891"
      overrideYaml:
        framew:
          type: http
          application:
            name: http-b
            tags:
              - key: k1
                value: v1
          config:
            appId: http-b
    framew-demo-http-b2:
      image: powerful-spring-mvc
      targetPort: 8891
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-http-b -Dframew.log.level=debug -Dframew.config.debug=true -Dserver.port=8891"
      overrideYaml:
        framew:
          type: mvc
          application:
            name: http-b
            tags:
              - key: k2
                value: v2
          config:
            appId: http-b
    framew-demo-dubbo-a:
      image: powerful-springboot-2
      targetPort: 22822
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-http-b -Dframew.log.level=debug -Dframew.config.debug=true -Dframew.port=22822"
      overrideYaml:
        framew:
          type: dubbo
          application:
            name: dubbo-a
            tags:
              - key: k3
                value: v3
          config:
            appId: dubbo-a
    framew-demo-dubbo-b:
      image: powerful-springboot-1
      targetPort: 22823
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-http-b -Dframew.log.level=debug -Dframew.config.debug=true -Dframew.port=22823"
      overrideYaml:
        framew:
          type: dubbo
          application:
            name: dubbo-b
            tags:
              - key: k2
                value: v2
          config:
            appId: dubbo-b
    framew-demo-dubbo-b2:
      image: powerful-springboot-1
      targetPort: 22823
      nodeIp: 10.182.2.116
      javaOpts: "-javaagent:/home/framew-agent/framew-agent.jar=framew-demo-http-b -Dframew.log.level=debug -Dframew.config.debug=true -Dframew.port=22823 -Dframew.app.version=0.0.1"
      overrideYaml:
        framew:
          type: dubbo
          application:
            name: dubbo-b
            tags:
              - key: k3
                value: v3
          config:
            appId: dubbo-b
commonAgentYaml:
  framew:
    version: 1.0
    framewServer: framew-server.skiff-app.svc.cluster.local
    application:
      zone: regionA
      group: default
      projectCode: project1
      envCode: prod
      projectEnv: prod
      version: 0.0.1
      desc: description
    metric:
      enable: true
    server:
      enable: true
      address: grpc://framew-server.skiff-app.svc.cluster.local:8981
    registry:
      enable: true
      address: http://framew-registry.skiff-app.svc.cluster.local/eureka/
    authority:
      server: http://platform-service-auth.skiff-app.svc.cluster.local
      retry: 3
      accessKey: 34fc391145724894b50344ea2e4fb595
      secretKey: 19e59bf60add4556aceb1fad26a28a91
    log:
      mode: user
      level: debug
    config:
      enable: true
      env: dev
      server: http://framew-config-service.skiff-app.svc.cluster.local
      namespaces:
        - name: application
          order: 2
          Public: true
        - name: application
