<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>zhranklin</groupId>
    <artifactId>powerful</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <artifactId>powerful-springboot</artifactId>

  <properties>
    <!--部署脚本中会被覆盖成provided-->
    <tomcatDepScope>compile</tomcatDepScope>
    <JavaVersion>17</JavaVersion>
    <java.version>${JavaVersion}</java.version>
    <springboot.version>2.7.7</springboot.version>
    <spring-cloud-starter-openfeign.version>3.1.8</spring-cloud-starter-openfeign.version>
    <spring-cloud-starter-loadbalancer.version>3.1.7</spring-cloud-starter-loadbalancer.version>
    <spring-cloud-starter-loadbalancer.artifactId>spring-cloud-starter-loadbalancer</spring-cloud-starter-loadbalancer.artifactId>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <!-- 排除内嵌的tomcat依赖-->
      <exclusions>
        <exclusion>
          <artifactId>spring-boot-starter-tomcat</artifactId>
          <groupId>org.springframework.boot</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- 引入上述步骤被排除的spring-boot-starter-tomcat，并将scope改为provided，保证编译正确-->
    <dependency>
      <artifactId>spring-boot-starter-tomcat</artifactId>
      <groupId>org.springframework.boot</groupId>
      <version>${springboot.version}</version>
      <scope>${tomcatDepScope}</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>zhranklin</groupId>
      <artifactId>powerful-core</artifactId>
      <version>0.0.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>${spring-cloud-starter-loadbalancer.artifactId}</artifactId>
      <version>${spring-cloud-starter-loadbalancer.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
      <version>${spring-cloud-starter-openfeign.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <!-- Import dependency management from Spring Boot -->
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${springboot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <finalName>powerful-boot-${springboot.version}-java${JavaVersion}</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
          <release>${java.version}</release>
          <encoding>UTF-8</encoding>
          <!--Springboot3.2.x: Set to true to generate metadata for reflection on method parameters.-->
          <parameters>true</parameters>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${springboot.version}</version>
        <executions>
          <execution><goals><goal>repackage</goal></goals></execution>
        </executions>
        <!-- 将tomcat在打包阶段依赖排除-->
        <configuration>
          <excludeGroupIds>org.apache.tomcat,org.apache.tomcat.embed</excludeGroupIds>
          <excludes>
            <exclude>
              <groupId>org.apache.dubbo</groupId>
              <artifactId>dubbo</artifactId>
            </exclude>
            <exclude>
              <groupId>com.alibaba</groupId>
              <artifactId>dubbo</artifactId>
            </exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
