targetMappings:
  a: localhost:8080
  b: localhost:8081
requestCases:
  test:
    call: <a>/aaa/bbb,
    by: http
    to:
      delay: 0
      responseFmt: "{{p(version)}}"
    description: 熔断, 正常会返回name和version
  echo_a_delay_1s:
    call: <a>
    by: http
    to:
      delay: 1
      responseFmt: "{{p(version)}}"
    description: 访问a, a加入1s时延后返回自己的版本
  echo_a_with_exception:
    call: <a>
    by: http
    to:
     responseFmt: "{{p(version)}}"
    errorByPercent: 60
    description: 访问a, 返回自己的版本
  redirect_a_b:
    call: <a>
    by: http
    to:
      times: 10
      collectBy: list
      call: <b>
      by: http
      to:
        delay: 0.1
        responseFmt: "{{p(version)}}"
      delay: 0.1
      responseFmt: "{{p(version)}} -> ({{statusCode()}}){{resultBody()}}"
  description: 让a访问b, 返回调用链路, 用版本表示调用结点
  redirect_a_c:
    call: <a>
    by: http
    to:
      call: <c>
      by: http
      to:
        delay: 0.5
        responseFmt: "{{p(version)}}"
      delay: 0.5
      responseFmt: "{{p(version)}} -> {{resultBody()}}"
    description: 让a访问c, 中间加入延迟, 返回调用链路, 用版本表示调用结点
