targetMappings:
  a: localhost:8080
  b: localhost:8081
requestCases:
  test:
    tell: <a>/aaa/bbb,
    by: http
    to:
      thenDelay: 0
      thenReturn: "{{p(version)}}"
    description: 熔断, 正常会返回name和version
  echo_a_delay_1s:
    tell: <a>
    by: http
    to:
      thenDelay: 1
      thenReturn: "{{p(version)}}"
    description: 访问a, a加入1s时延后返回自己的版本
  echo_a_with_exception:
    tell: <a>
    by: http
    to:
     thenReturn: "{{p(version)}}"
    thenThrowByPercent: 60
    description: 访问a, 返回自己的版本
  redirect_a_b:
    tell: <a>
    by: http
    to:
      forTimes: 10
      collectBy: list
      tell: <b>
      by: http
      to:
        thenDelay: 0.1
        thenReturn: "{{p(version)}}"
      thenDelay: 0.1
      thenReturn: "{{p(version)}} -> ({{statusCode()}}){{resultBody()}}"
  description: 让a访问b, 返回调用链路, 用版本表示调用结点
  redirect_a_c:
    tell: <a>
    by: http
    to:
      tell: <c>
      by: http
      to:
        thenDelay: 0.5
        thenReturn: "{{p(version)}}"
      thenDelay: 0.5
      thenReturn: "{{p(version)}} -> {{resultBody()}}"
    description: 让a访问c, 中间加入延迟, 返回调用链路, 用版本表示调用结点
