{{- range $name, $secret := .Values.defaults.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ include "namespace" $}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $secret | quote }}
---
{{- end }}