{{- range $name, $secret := .Values.defaults.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Name }}
  labels:
    release: {{ $.Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $secret | quote }}
---
{{- end }}