{{- $ingressHost := tpl .Values.ingressHost $ }}
{{ if $ingressHost }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: powerful
  namespace: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    release: {{ .Release.Name }}
spec:
  rules:
  - host: {{ $ingressHost }}
    http:
      paths:
      - backend:
          serviceName: powerful-cases
          servicePort: 80
{{- end }}
